Repository InfiniView-AI/MotionMingle, pull requests merged in 2024-03, with the labels that each got.

#104 79 set up backend test
  .github/workflows/action-test-demo.yml
  .gitignore
  requirements.txt
  test/test_server.py
Labels: tests

#113 112 deliverable 6 verification and validation report
  .coverage
  docs/VnVPlan/VnVPlan.pdf
  docs/VnVPlan/VnVPlan.tex
  docs/VnVReport/VnVReport.pdf
  docs/VnVReport/VnVReport.tex
  docs/VnVReport/surveyp1.png
  docs/VnVReport/surveyp2.png
  docs/VnVReport/surveyp3.png
  docs/VnVReport/surveyp4.png
  docs/VnVReport/surveyp5.png
Labels: documentation

#120 clear all transformed streams on track ends
  src/back/server.py
Labels: bug, development

#122 111 client enhancement
  src/client/favicon.ico
  src/client/index.html
  src/client/src/modules/Auth.tsx
  src/client/src/modules/Instructor.tsx
  src/client/src/modules/Practitioner.tsx
Labels: enhancement

#140 added poster pdf
  docs/Presentations/EXPO/4G06 Expo Poster.pdf
Labels: documentation
